---
- name: Конфигурация сервера PostgreSQL 16 на Debian
  hosts: dbservers
  become: true
  become_user: root
  become_method: su
  become_flags: "-"

  vars_files:
    - postgresql_config.yml

  tasks:

    # Обновление системы и установка зависимостей
    - name: Обновление списка пакетов
      ansible.builtin.apt:
        update_cache: yes

    - name: Полное обновление системы
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Установка python3-psycopg
      ansible.builtin.apt:
        name: python3-psycopg
        state: present

    - name: Установка postgresql-common
      ansible.builtin.apt:
        name: postgresql-common
        state: present

    - name: Добавление репозитория PostgreSQL
      ansible.builtin.command: /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y

    - name: Повторное обновление списка пакетов
      ansible.builtin.apt:
        update_cache: yes


    # Установка PostgreSQL
    - name: Установка PostgreSQL 16
      ansible.builtin.apt:
        name: postgresql-16
        state: present

    - name: Запуск и включение PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: yes


    # Настройка PostgreSQL
    - name: Разрешение довереного подключения для localhost
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/16/main/pg_hba.conf
        contype: local
        users: postgres
        databases: all
        method: trust

    - name: Перезапуск PostgreSQL для применения изменений
      ansible.builtin.service:
        name: postgresql
        state: restarted

    - name: Изменение пароля postgres для внешнего подключения
      community.postgresql.postgresql_user:
        name: postgres
        password: postgres

    - name: Установка параметра listen_addresses
      community.postgresql.postgresql_set:
        name: listen_addresses
        value: "*"

    - name: Настройка max_connections для PostgreSQL
      community.postgresql.postgresql_set:
        name: max_connections
        value: "{{ postgresql.max_connections * 2 }}"

    - name: Настройка shared_buffers для PostgreSQL
      community.postgresql.postgresql_set:
        name: shared_buffers
        value: "{{ (ansible_memtotal_mb * 0.5)|int }}MB"

    - name: Настройка temp_buffers для PostgreSQL
      community.postgresql.postgresql_set:
        name: temp_buffers
        value: "{{ postgresql.temp_buffers }}"

    - name: Настройка work_mem для PostgreSQL
      community.postgresql.postgresql_set:
        name: work_mem
        value: "{{ postgresql.work_mem }}"

    - name: Настройка maintenance_work_mem для PostgreSQL
      community.postgresql.postgresql_set:
        name: maintenance_work_mem
        value: "{{ postgresql.maintenance_work_mem }}"

    - name: Запрет довереного подключения для localhost
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/16/main/pg_hba.conf
        contype: local
        users: postgres
        databases: all
        method: peer

    - name: Разрешение подключения для всех хостов (pg_hba.conf)
      community.postgresql.postgresql_pg_hba:
        dest: /etc/postgresql/16/main/pg_hba.conf
        contype: host
        users: all
        source: "{{ postgresql.source_ip }}"
        databases: all
        method: scram-sha-256

    - name: Перезапуск PostgreSQL для применения изменений
      ansible.builtin.service:
        name: postgresql
        state: restarted


    # Настройка лимитов и параметров ядра
    - name: Установка лимитов для процессов PostgreSQL (limits.conf)
      ansible.builtin.lineinfile:
        path: /etc/security/limits.conf
        line: "{{ item }}"
        create: yes
      loop:
        - "postgres    soft    nofile    65536"
        - "postgres    hard    nofile    65536"

    - name: Настройка ядра для большего числа файлов (sysctl.conf)
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "fs.file-max = 1000000"
        create: yes

    - name: Настройка дополнительных параметров sysctl (vm.min_free_kbytes)
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "vm.min_free_kbytes = 4194304"
        create: yes

    - name: Настройка дополнительных параметров sysctl (vm.swappiness)
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "vm.swappiness = 1"
        create: yes

    - name: Применение изменений ядра
      ansible.builtin.command:
        cmd: sysctl -p
        creates: /proc/sys/fs/file-max


    # Настройка фаервола
    - name: Установка пакета ufw
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Открытие порта 5432 для PostgreSQL
      ansible.builtin.ufw:
        rule: allow
        port: 5432
        proto: tcp

    - name: Разрешение SSH
      ansible.builtin.ufw:
        rule: allow
        name: 'OpenSSH'

    - name: Включение фаервола
      ansible.builtin.ufw:
        state: enabled
